```yaml
openapi: 3.0.3
info:
  title: Notification Service API
  description: API to manage notifications across the warranty and repair system
  version: 1.0.0
servers:
  - url: "http://localhost:8085"
    description: Development Server

tags:
  - name: notifications
    description: Manage notifications

paths:
  /api/v1/notifications/customer/{customerId}:
    get:
      summary: Get notifications by customer ID
      description: Returns a list of notifications for a specific customer
      tags: [notifications]
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: List of notifications for the customer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NotificationResponseDto"

  /api/v1/notifications/related/{relatedEntityId}:
    get:
      summary: Get notifications by related entity ID
      description: Returns a list of notifications for a specific related entity (e.g., warranty request)
      tags: [notifications]
      parameters:
        - name: relatedEntityId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: List of notifications for the related entity
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NotificationResponseDto"

components:
  schemas:
    NotificationResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        customerId:
          type: integer
          format: int32
        type:
          type: string
          enum: [REPAIR_CREATED, REPAIR_REJECTED, REPAIR_APPROVED, PRODUCT_RECEIVED, DIAGNOSIS_STARTED, REPAIR_IN_PROGRESS, REPAIR_COMPLETED, PRODUCT_SHIPPING, PRODUCT_DELIVERED, FEEDBACK_REQUEST, WARRANTY_APPROVED, WARRANTY_REJECTED, WARRANTY_RECEIVED, WARRANTY_COMPLETED]
        warrantyRequestId:
          type: integer
          format: int32
        email:
          type: string
          format: email
        subject:
          type: string
        status:
          type: string
          enum: [PENDING, SENT, FAILED]
        sentAt:
          type: string
          format: date-time

    NotificationRequestDto:
      type: object
      properties:
        customerId:
          type: integer
          format: int32
        type:
          type: string
          enum: [REPAIR_CREATED, REPAIR_REJECTED, REPAIR_APPROVED, PRODUCT_RECEIVED, DIAGNOSIS_STARTED, REPAIR_IN_PROGRESS, REPAIR_COMPLETED, PRODUCT_SHIPPING, PRODUCT_DELIVERED, FEEDBACK_REQUEST, WARRANTY_APPROVED, WARRANTY_REJECTED, WARRANTY_RECEIVED, WARRANTY_COMPLETED]
        warrantyRequestId:
          type: integer
          format: int32
        customerName:
          type: string
        email:
          type: string
          format: email
        message:
          type: string
        productName:
          type: string
```