```yaml
openapi: 3.0.3
info:
  title: Technician Service API
  description: API to manage technicians
  version: 1.0.0
servers:
  - url: "http://localhost:8086"
    description: Development Server

tags:
  - name: technicians
    description: Manage technicians

paths:
  /api/v1/technicians:
    get:
      summary: Get all technicians
      description: Returns a list of all technicians in the system
      tags: [technicians]
      responses:
        "200":
          description: List of technicians
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TechnicianResponse"
    post:
      summary: Create a new technician
      description: Creates a new technician in the system
      tags: [technicians]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TechnicianRequest"
      responses:
        "201":
          description: Technician created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TechnicianResponse"
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/technicians/{id}:
    get:
      summary: Get technician by ID
      description: Returns detailed information of a technician by ID
      tags: [technicians]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Technician information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TechnicianResponse"
        "404":
          description: Technician not found
    put:
      summary: Update technician
      description: Updates an existing technician's information
      tags: [technicians]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TechnicianRequest"
      responses:
        "200":
          description: Technician updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TechnicianResponse"
        "400":
          description: Invalid data
        "404":
          description: Technician not found
    delete:
      summary: Delete technician
      description: Deletes a technician from the system
      tags: [technicians]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "204":
          description: Technician deleted successfully
        "404":
          description: Technician not found

  /api/v1/technicians/email/{email}:
    get:
      summary: Get technician by email
      description: Returns detailed information of a technician by email
      tags: [technicians]
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
            format: email
      responses:
        "200":
          description: Technician information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TechnicianResponse"
        "404":
          description: Technician not found

  /api/v1/technicians/active:
    get:
      summary: Get all active technicians
      description: Returns a list of all active technicians
      tags: [technicians]
      responses:
        "200":
          description: List of active technicians
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TechnicianResponse"

  /api/v1/technicians/specialization/{specialization}:
    get:
      summary: Get technicians by specialization
      description: Returns a list of technicians with the specified specialization
      tags: [technicians]
      parameters:
        - name: specialization
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of technicians with the specified specialization
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TechnicianResponse"

  /api/v1/technicians/{id}/toggle-status:
    patch:
      summary: Toggle technician active status
      description: Toggles the active status of a technician (active <-> inactive)
      tags: [technicians]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Status toggled successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TechnicianResponse"
        "404":
          description: Technician not found

components:
  schemas:
    TechnicianRequest:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        specialization:
          type: string
        yearsOfExperience:
          type: integer
          format: int32
          minimum: 0
        isActive:
          type: boolean
          default: true

    TechnicianResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        specialization:
          type: string
        yearsOfExperience:
          type: integer
          format: int32
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        timestamp:
          type: string
          format: date-time
```