package com.example.service_warranty.models;

public enum NotificationType {
    REPAIR_CREATED,
    REPAIR_REJECTED,
    REPAIR_APPROVED,
    PRODUCT_RECEIVED,
    DIAGNOSIS_STARTED,
    REPAIR_IN_PROGRESS,
    REPAIR_COMPLETED,
    PRODUCT_SHIPPING,
    PRODUCT_DELIVERED,
    FEEDBACK_REQUEST,
    WARRANTY_APPROVED,
    WARRANTY_REJECTED,
    WARRANTY_RECEIVED,
    WARRANTY_COMPLETED
}

