openapi: 3.0.3
info:
  title: Customer Service API
  description: API để quản lý thông tin khách hàng
  version: 1.0.0
servers:
  - url: "http://localhost:8081"
    description: Development Server

tags:
  - name: customers
    description: Quản lý thông tin khách hàng
  - name: purchases
    description: Quản lý thông tin mua hàng
  - name: warranty
    description: Quản lý thông tin bảo hành

paths:
  /api/v1/customers:
    get:
      summary: Lấy danh sách tất cả khách hàng
      description: Trả về danh sách tất cả khách hàng trong hệ thống
      tags: [customers]
      responses:
        "200":
          description: Danh sách khách hàng
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"
    post:
      summary: Tạo mới khách hàng
      description: Tạo mới thông tin khách hàng trong hệ thống
      tags: [customers]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "201":
          description: Khách hàng được tạo thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        "400":
          description: Dữ liệu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/customers/{id}:
    get:
      summary: Lấy thông tin khách hàng theo ID
      description: Trả về thông tin chi tiết của khách hàng theo ID cung cấp
      tags: [customers]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Thông tin khách hàng
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        "404":
          description: Không tìm thấy khách hàng với ID cung cấp
    put:
      summary: Cập nhật thông tin khách hàng
      description: Cập nhật thông tin của khách hàng theo ID cung cấp
      tags: [customers]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        "200":
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        "400":
          description: Dữ liệu không hợp lệ
        "404":
          description: Không tìm thấy khách hàng với ID cung cấp
    delete:
      summary: Xóa khách hàng
      description: Xóa thông tin khách hàng theo ID cung cấp
      tags: [customers]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "204":
          description: Xóa thành công
        "404":
          description: Không tìm thấy khách hàng với ID cung cấp

  /api/v1/customers/email:
    get:
      summary: Lấy thông tin khách hàng theo email
      description: Trả về thông tin chi tiết của khách hàng theo email cung cấp
      tags: [customers]
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            format: email
      responses:
        "200":
          description: Thông tin khách hàng
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        "404":
          description: Không tìm thấy khách hàng với email cung cấp

  /api/v1/customers/{customerId}/purchase:
    get:
      summary: Lấy tất cả các đơn mua hàng của khách hàng
      description: Trả về danh sách các đơn mua hàng của khách hàng theo ID cung cấp
      tags: [purchases]
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Danh sách đơn mua hàng
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PurchaseDTO"

  /api/v1/customers/{customerId}/purchase/{purchaseId}:
    get:
      summary: Lấy chi tiết đơn mua hàng
      description: Trả về chi tiết đơn mua hàng theo ID khách hàng và ID đơn hàng
      tags: [purchases]
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: purchaseId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Chi tiết đơn mua hàng
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseDTO"
        "404":
          description: Không tìm thấy đơn mua hàng

  /api/v1/customers/purchase/{productId}:
    get:
      summary: Lấy đơn mua hàng theo ID sản phẩm
      description: Trả về đơn mua hàng có chứa sản phẩm theo ID sản phẩm cung cấp
      tags: [purchases]
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Đơn mua hàng
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseDTO"
        "404":
          description: Không tìm thấy đơn mua hàng với sản phẩm có ID cung cấp

  /api/v1/customers/warranty/requests:
    post:
      summary: Tạo mới yêu cầu bảo hành
      description: Tạo mới yêu cầu bảo hành cho sản phẩm
      tags: [warranty]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WarrantyRequestDTO"
      responses:
        "201":
          description: Yêu cầu bảo hành được tạo thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WarrantyRequestDTO"
        "400":
          description: Dữ liệu không hợp lệ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/customers/warranty/requests/{id}:
    get:
      summary: Lấy thông tin yêu cầu bảo hành theo ID
      description: Trả về thông tin chi tiết của yêu cầu bảo hành theo ID cung cấp
      tags: [warranty]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Thông tin yêu cầu bảo hành
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WarrantyRequestDTO"
        "404":
          description: Không tìm thấy yêu cầu bảo hành với ID cung cấp

  /api/v1/customers/warranty/requests/customer/{customerId}:
    get:
      summary: Lấy danh sách yêu cầu bảo hành theo ID khách hàng
      description: Trả về danh sách yêu cầu bảo hành của khách hàng theo ID cung cấp
      tags: [warranty]
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Danh sách yêu cầu bảo hành
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WarrantyRequestDTO"

  /api/v1/customers/warranty/requests/status/{status}:
    get:
      summary: Lấy danh sách yêu cầu bảo hành theo trạng thái
      description: Trả về danh sách yêu cầu bảo hành có trạng thái cung cấp
      tags: [warranty]
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Danh sách yêu cầu bảo hành
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WarrantyRequestDTO"

  /api/v1/customers/warranty/requests/{id}/status:
    put:
      summary: Cập nhật trạng thái yêu cầu bảo hành
      description: Cập nhật trạng thái của yêu cầu bảo hành theo ID cung cấp
      tags: [warranty]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                notes:
                  type: string
                performedBy:
                  type: string
      responses:
        "200":
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WarrantyRequestDTO"
        "400":
          description: Dữ liệu không hợp lệ
        "404":
          description: Không tìm thấy yêu cầu bảo hành với ID cung cấp

  /api/v1/customers/warranty/requests/{id}/repair:
    put:
      summary: Cập nhật ID sửa chữa cho yêu cầu bảo hành
      description: Cập nhật ID sửa chữa cho yêu cầu bảo hành theo ID cung cấp
      tags: [warranty]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - repairId
              properties:
                repairId:
                  type: integer
                performedBy:
                  type: string
      responses:
        "200":
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WarrantyRequestDTO"
        "400":
          description: Dữ liệu không hợp lệ
        "404":
          description: Không tìm thấy yêu cầu bảo hành với ID cung cấp

  /api/v1/customers/warranty/requests/{id}/history:
    get:
      summary: Lấy lịch sử yêu cầu bảo hành
      description: Trả về lịch sử của yêu cầu bảo hành theo ID cung cấp
      tags: [warranty]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Lịch sử yêu cầu bảo hành
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WarrantyHistoryDTO"

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
        address:
          type: string

    PurchaseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        purchaseDate:
          type: string
        invoiceNumber:
          type: string
        totalAmount:
          type: number
          format: double
        paymentMethod:
          type: string
        customerId:
          type: integer
          format: int32
        customerName:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/PurchaseItemDTO"

    PurchaseItemDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        purchaseId:
          type: integer
          format: int32
        productId:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        unitPrice:
          type: number
          format: decimal

    WarrantyRequestDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        customerId:
          type: integer
          format: int32
        customerName:
          type: string
          readOnly: true
        productName:
          type: string
        serialNumber:
          type: string
        issueDescription:
          type: string
        imageUrls:
          type: array
          items:
            type: string
        status:
          type: string
          default: "PENDING"
        submissionDate:
          type: string
          format: date-time
          readOnly: true
        expirationDate:
          type: string
          format: date
        validationNotes:
          type: string
        repairId:
          type: integer
          format: int32

    WarrantyHistoryDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        warrantyRequestId:
          type: integer
          format: int32
        status:
          type: string
        notes:
          type: string
        performedBy:
          type: string
        performedAt:
          type: string
          format: date-time
          readOnly: true

    Error:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string