package com.example.service_warranty.dto;

public enum NotificationType {
    WARRANTY_CREATE,
    WARRANTY_REJECT,
    WARRANTY_APPROVED,
    PRODUCT_RECEIVED,
    DIAGNOSIS_STARTED,
    REPAIR_IN_PROGRESS,
    REPAIR_COMPLETED,
    PRODUCT_SHIPPING,
    PRODUCT_DELIVERED,
    FEEDBACK_REQUEST
}
